version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5198:5198"
      - "7164:7164"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=boa-fe-db;User Id=admin;Password=Abc@123456789;"


  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Abc@123456789"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "boa-fe-db"
      MSSQL_USER: "admin"
      MSSQL_PASSWORD: "Abc@123456789"